In [9]:
import pandas as pd
import numpy as np

cheese = pd.DataFrame(
  {
  "first": ["John", "Mary"],
  "last": ["Doe", "Bo"],
  "height": [5.5, 6.0],
  "weight": [130, 150],
 }
)
pd.melt(cheese, id_vars=["first", "last"])

  first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

In [14]:
cheese = pd.DataFrame(
  {
  "first": ["John", "Mary"],
  "last": ["Doe", "Bo"],
  "height": [5.5, 6.0],
  "weight": [130, 150],
 }
)

In [16]:
cheese = pd.DataFrame(
  {
  "first": ["John", "Mary"],
  "last": ["Doe", "Bo"],
  "height": [5.5, 6.0],
  "weight": [130, 150],
 }
)
cheese

  first last  height  weight
0  John  Doe     5.5     130
1  Mary   Bo     6.0     150

In [10]:
cheese.set_index(["first", "last"]).stack()

first  last
John   Doe   height      5.5
             weight    130.0
Mary   Bo    height      6.0
             weight    150.0
dtype: float64

In [13]:
df = pd.DataFrame(
 {
 "x": np.random.uniform(1.0, 168.0, 12),
 "y": np.random.uniform(7.0, 334.0, 12),
"z": np.random.uniform(1.7, 20.7, 12),
 "month": [5, 6, 7] * 4,
"week": [1, 2] * 6,
 }
)
mdf = pd.melt(df, id_vars=["month", "week"])
pd.pivot_table(
mdf,
values="value",
index=["variable", "week"],
    columns=["month"],
 aggfunc=np.mean,
 )

month                   5           6           7
variable week
x        1      52.098864  117.549806  100.822356
         2     102.804165  126.960022   94.914576
y        1     251.263278  180.720211  197.537983
         2     274.657673  130.927481   40.047018
z        1      16.352021   18.003639   11.726437
         2      11.933806    8.916792   11.747056

In [17]:
#86

In [22]:
df = pd.DataFrame(
 {
 "Animal": [
 "Animal1",
 "Animal2",
 "Animal3",
 "Animal2",
 "Animal1",
 "Animal2",
 "Animal3",
 ],
 "FeedType": ["A", "B", "A", "A", "B", "B", "A"],
 "Amount": [10, 7, 4, 2, 5, 6, 2],
}
 )

df.pivot_table(values="Amount", index="Animal", columns="FeedType", aggfunc="sum")

FeedType     A     B
Animal
Animal1   10.0   5.0
Animal2    2.0  13.0
Animal3    6.0   NaN

In [24]:
df.groupby(["Animal", "FeedType"])["Amount"].sum()

Animal   FeedType
Animal1  A           10
         B            5
Animal2  A            2
         B           13
Animal3  A            6
Name: Amount, dtype: int64